<a href="https://colab.research.google.com/github/Julia-Wambua/CDAV-/blob/main/Teen_Mental_Health_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PANDAS**
## This is a library used to manipulate data in python

In [1]:
!pip install pandas

# pandas has already been installed in google collab hence it says
# requirement already satisfied

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
pd.__version__
# a series is a list that grew up. It carries labels on the left(index of each item)
# and a single dtype at the bottom
counties = pd.Series([14397073, 1208333, 2162202, 11578731])
print(counties)

0    14397073
1     1208333
2     2162202
3    11578731
dtype: int64

In [4]:
df = pd.read_csv("/content/Teen_Mental_Health_Dataset - Teen_Mental_Health_Dataset.csv.csv")# path to the file containing the data
df.head(10) # shows the first 5 values with nothing in the brackets

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0
7,16,male,4.0,Both,4.2,0.5,2.40,1.3,low,6,10,5,0
8,19,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1,10,9,0
9,15,male,1.9,TikTok,4.9,1.5,3.77,1.1,high,1,1,4,0

In [5]:
df.tail(12)# shows the last 5 values with nothing in the brackets

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1188,17,female,7.4,Instagram,7.4,2.0,3.76,1.7,high,10,1,4,0
1189,14,female,1.6,TikTok,4.8,2.4,2.97,1.9,low,9,9,10,0
1190,17,female,3.8,Instagram,8.4,0.9,3.60,1.9,high,1,2,2,0
1191,19,male,8.0,TikTok,4.7,0.5,2.18,0.6,medium,8,8,6,1
1192,13,male,7.8,TikTok,5.9,1.5,3.31,1.9,high,10,1,10,0
1193,13,female,7.2,Instagram,8.1,2.1,2.52,0.4,medium,3,3,7,0
1194,17,male,2.0,Both,4.5,1.7,2.65,0.0,medium,9,4,2,0
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [6]:
df.shape # total number of columns and rows in your dataset

(1200, 13)

In [7]:
df.info() # the most useful method in pandas
# showa a breakdown of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB

In [8]:
df.describe() # the numbers at a glance
# shows the measures of central tendency of your dataset(mean,total no of entries etc)

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

# These do not have brackets since they are **ATTRIBUTES**

In [9]:
df.columns # the column names

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='object')

In [10]:
df.dtypes # the tpye of each column

age                           int64
gender                       object
daily_social_media_hours    float64
platform_usage               object
sleep_hours                 float64
screen_time_before_sleep    float64
academic_performance        float64
physical_activity           float64
social_interaction_level     object
stress_level                  int64
anxiety_level                 int64
addiction_level               int64
depression_label              int64
dtype: object

In [11]:
df.index # the row labels

RangeIndex(start=0, stop=1200, step=1)

In [12]:
df.size # total number of cells

15600

In [13]:
df['age'].unique() # what values appear in the dataset under the given column

array([14, 19, 17, 15, 18, 16, 13])

In [14]:
df['age'].nunique() # how many distinct values are present in a given column

7

In [15]:
df["gender"].unique()

array(['male', 'female'], dtype=object)

In [16]:
df["gender"].nunique()

2

# Selecting columns - use square brackets **[]**

In [17]:
df[["age", "gender"]]  # two columns - DataFrame

      age  gender
0      14    male
1      19  female
2      17  female
3      15    male
4      15  female
...   ...     ...
1195   18  female
1196   16    male
1197   14  female
1198   15    male
1199   16  female

[1200 rows x 2 columns]

In [18]:
df["age"] # one column - a Series

0       14
1       19
2       17
3       15
4       15
        ..
1195    18
1196    16
1197    14
1198    15
1199    16
Name: age, Length: 1200, dtype: int64

In [19]:
df[["age", "gender", "depression_label"]] # dataframe

      age  gender  depression_label
0      14    male                 0
1      19  female                 0
2      17  female                 0
3      15    male                 0
4      15  female                 0
...   ...     ...               ...
1195   18  female                 0
1196   16    male                 0
1197   14  female                 0
1198   15    male                 0
1199   16  female                 0

[1200 rows x 3 columns]

# .**loc** and .**iloc**

In [20]:
df.loc[2, "age"] # row 2, column named age
# allows you to input the specific column name

np.int64(17)

In [21]:
df.iloc[2,0] # third row, first column (age) (incorporates indexes)
# you input the index of the desired column

np.int64(17)

In [22]:
df.iloc[5,0] # 6th row, first column(age)

np.int64(19)

In [23]:
df.iloc[2,2]

np.float64(1.3)

In [24]:
df.loc[0] # shows you info in the first row only

age                                14
gender                           male
daily_social_media_hours          7.9
platform_usage              Instagram
sleep_hours                       7.4
screen_time_before_sleep          2.9
academic_performance             3.01
physical_activity                 1.5
social_interaction_level          low
stress_level                        2
anxiety_level                       2
addiction_level                     1
depression_label                    0
Name: 0, dtype: object

In [25]:
df.loc[0:2] # shows you the first 3 rows, does not incorporate use of indices
# which is wht the first 3 rows are shown

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0

In [26]:
df.iloc[0]

age                                14
gender                           male
daily_social_media_hours          7.9
platform_usage              Instagram
sleep_hours                       7.4
screen_time_before_sleep          2.9
academic_performance             3.01
physical_activity                 1.5
social_interaction_level          low
stress_level                        2
anxiety_level                       2
addiction_level                     1
depression_label                    0
Name: 0, dtype: object

In [27]:
df.iloc[0:2] # showa you the first and second row.....indices are applied

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0

# Filtering out data

In [28]:
df["gender"] == "female"
# filters out rows with the gender female and returns True for them

0       False
1        True
2        True
3       False
4        True
        ...
1195     True
1196    False
1197     True
1198    False
1199     True
Name: gender, Length: 1200, dtype: bool

In [31]:
df["age"] == 14
# rows with their age as 14

0        True
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197     True
1198    False
1199    False
Name: age, Length: 1200, dtype: bool

In [32]:
df["gender"] != "female"
# shows True for the rows whose gender value is male

0        True
1       False
2       False
3        True
4       False
        ...
1195    False
1196     True
1197    False
1198     True
1199    False
Name: gender, Length: 1200, dtype: bool

In [33]:
df["age"] > 14
# shows True for the rows whose age value is greater than 14

0       False
1        True
2        True
3        True
4        True
        ...
1195     True
1196     True
1197    False
1198     True
1199     True
Name: age, Length: 1200, dtype: bool

In [43]:
s = pd.Series([10,25,30,45])
s > 20

0    False
1     True
2     True
3     True
dtype: bool

In [37]:
df[ df ["age"] > 14 ]
# from this dataframe, give me rows where age is greater than 14

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194,17,male,2.0,Both,4.5,1.7,2.65,0.0,medium,9,4,2,0
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

# Giving your mask a name rather than having one line of code e.g

     df[df ["age"] > 14]
     is_gender = df["gender"] == "female"
     is_greater = df["age"] > 14
     df[is_gender & is_greater]

In [40]:
is_gender = df["gender"] == "female"
is_greater = df["age"] > 14
df[is_gender & is_greater]

# shows rows whose gender is female and whose age is greater than 14
# both conditions have to be met to get the correct output

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,19,female,6.6,Both,9.0,2.9,2.47,1.7,medium,3,7,9,0
1188,17,female,7.4,Instagram,7.4,2.0,3.76,1.7,high,10,1,4,0
1190,17,female,3.8,Instagram,8.4,0.9,3.60,1.9,high,1,2,2,0
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [47]:
is_gender = df["gender"] == "female"
is_greater = df["age"] > 14
df[is_gender & is_greater]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,19,female,6.6,Both,9.0,2.9,2.47,1.7,medium,3,7,9,0
1188,17,female,7.4,Instagram,7.4,2.0,3.76,1.7,high,10,1,4,0
1190,17,female,3.8,Instagram,8.4,0.9,3.60,1.9,high,1,2,2,0
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [54]:
is_gender2 = df[df["age"] > 14]
is_gender2.shape # number of rows and columns whose age value = 14

(847, 13)

In [55]:
len(is_gender2) # number of rows only whose age value = 14

847

# Two conditions at once
*   and   **(&)**
*   or    **(|)**

In [58]:
# female and 14
df[(df["age"]== 14) & (df["gender"] == "female")] # and(&)
# both conditions have to be true for you to get an output

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
15,14,female,3.6,Both,5.3,0.6,2.99,0.3,high,4,10,2,0
19,14,female,1.2,Instagram,7.6,1.0,3.85,0.8,high,8,4,6,0
26,14,female,5.7,Both,8.7,0.6,2.64,0.1,low,8,9,4,0
42,14,female,7.3,Instagram,7.7,1.4,3.42,0.3,medium,6,1,8,0
45,14,female,4.5,TikTok,4.8,0.9,2.22,0.8,low,1,4,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1140,14,female,7.8,TikTok,4.7,2.2,3.53,0.6,low,5,8,2,0
1150,14,female,1.1,Both,5.4,1.6,3.34,1.5,medium,4,5,8,0
1171,14,female,5.7,TikTok,6.4,1.9,3.30,1.3,high,6,8,5,0
1189,14,female,1.6,TikTok,4.8,2.4,2.97,1.9,low,9,9,10,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0

In [61]:
# female or 14
df[(df["age"] == 14) | (df["gender"] == "female")] # or
# either of the conditions can be true to get an output

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,17,female,3.8,Instagram,8.4,0.9,3.60,1.9,high,1,2,2,0
1193,13,female,7.2,Instagram,8.1,2.1,2.52,0.4,medium,3,3,7,0
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

# Not, and one-of-many
*   **(-)** means *NOT*
*   .**isin()** - *one of many*

In [65]:
# Not age (-) means not
df[-(df["age"] == 14 )]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194,17,male,2.0,Both,4.5,1.7,2.65,0.0,medium,9,4,2,0
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [66]:
# one of several, without a long chain of or's
df[df["age"].isin([14,15,16])] # gives you colums with age as 14,15 or 16

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
7,16,male,4.0,Both,4.2,0.5,2.40,1.3,low,6,10,5,0
9,15,male,1.9,TikTok,4.9,1.5,3.77,1.1,high,1,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,14,female,1.6,TikTok,4.8,2.4,2.97,1.9,low,9,9,10,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [67]:
df[-df["age"].isin([14,15,16])]
# gives rows of all ages EXCEPT 14,15 and 16
# (-) mean NOT

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0
8,19,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1,10,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,19,male,8.0,TikTok,4.7,0.5,2.18,0.6,medium,8,8,6,1
1192,13,male,7.8,TikTok,5.9,1.5,3.31,1.9,high,10,1,10,0
1193,13,female,7.2,Instagram,8.1,2.1,2.52,0.4,medium,3,3,7,0
1194,17,male,2.0,Both,4.5,1.7,2.65,0.0,medium,9,4,2,0
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0

# Ranges and a readable alternative
*   **.between()** - inclusive at both ends
*  **.query()** - the same filter, written as a sentence

In [68]:
# between - inclusive at both ends, NO EXCLUSIVE VALUES
df[df["age"].between(14,16)] # gives rows whose ages are 14,15 and 16

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
7,16,male,4.0,Both,4.2,0.5,2.40,1.3,low,6,10,5,0
9,15,male,1.9,TikTok,4.9,1.5,3.77,1.1,high,1,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,14,female,1.6,TikTok,4.8,2.4,2.97,1.9,low,9,9,10,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [69]:
# query - the same filter, written as a entence
df.query("14 <= age <= 16")

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
7,16,male,4.0,Both,4.2,0.5,2.40,1.3,low,6,10,5,0
9,15,male,1.9,TikTok,4.9,1.5,3.77,1.1,high,1,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,14,female,1.6,TikTok,4.8,2.4,2.97,1.9,low,9,9,10,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

# Before you filter see what is there

In [71]:
df["gender"].value_counts() # how many males & females are there

gender
male      615
female    585
Name: count, dtype: int64

In [72]:
df["gender"].value_counts(dropna=False) # counts the missing values in case any are present

gender
male      615
female    585
Name: count, dtype: int64

In [73]:
df["gender"].unique()

array(['male', 'female'], dtype=object)

In [74]:
df["gender"].nunique()

2

# Data Cleaning

In [75]:
df.isna() # True where a value is missing

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,False,False,False,False,False,False,False,False,False,False,False,False,False
1196,False,False,False,False,False,False,False,False,False,False,False,False,False
1197,False,False,False,False,False,False,False,False,False,False,False,False,False
1198,False,False,False,False,False,False,False,False,False,False,False,False,False
1199,False,False,False,False,False,False,False,False,False,False,False,False,False

In [76]:
df.isna().sum() # count per column
# use this line on every dataset you ever load

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

In [77]:
df.isna().sum().sum() # total across the whole table

np.int64(0)

In [78]:
df.isna().mean()*100 # percentage missiong per column

age                         0.0
gender                      0.0
daily_social_media_hours    0.0
platform_usage              0.0
sleep_hours                 0.0
screen_time_before_sleep    0.0
academic_performance        0.0
physical_activity           0.0
social_interaction_level    0.0
stress_level                0.0
anxiety_level               0.0
addiction_level             0.0
depression_label            0.0
dtype: float64

# Finding Duplicates

In [80]:
df.duplicated().sum() # how many repeated

np.int64(0)

In [81]:
df[df.duplicated()] # LOOK at them be

Empty DataFrame
Columns: [age, gender, daily_social_media_hours, platform_usage, sleep_hours, screen_time_before_sleep, academic_performance, physical_activity, social_interaction_level, stress_level, anxiety_level, addiction_level, depression_label]
Index: []

# Dropping duplicates

In [82]:
df.drop_duplicates()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [6]:
df.drop_duplicates(subset=["age"])

NameError: name 'df' is not defined

In [ ]:
df.drop_duplicates(subset=["age"], keep=")

# Fixing column names

# Replacing bad values

# Dropping what you do not need

# Making a new column from a condition

# Changing values in place with **.loc**

# Data types

In [7]:
df.dtypes

NameError: name 'df' is not defined