<a href="https://colab.research.google.com/github/Julia-Wambua/CDAV-/blob/main/Teen_Mental_Health_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PANDAS**
## This is a library used to manipulate data in python

In [7]:
!pip install pandas

# pandas has already been installed in google collab hence it says
# requirement already satisfied

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [9]:
import pandas as pd
pd.__version__
# a series is a list that grew up. It carries labels on the left(index of each item)
# and a single dtype at the bottom
counties = pd.Series([14397073, 1208333, 2162202, 11578731])
print(counties)

0    14397073
1     1208333
2     2162202
3    11578731
dtype: int64

In [25]:
df = pd.read_csv("/content/Teen_Mental_Health_Dataset - Teen_Mental_Health_Dataset.csv.csv")# path to the file containing the data
df.head(10) # shows the first 5 values with nothing in the brackets

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0
7,16,male,4.0,Both,4.2,0.5,2.40,1.3,low,6,10,5,0
8,19,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1,10,9,0
9,15,male,1.9,TikTok,4.9,1.5,3.77,1.1,high,1,1,4,0

In [26]:
df.tail(12)# shows the last 5 values with nothing in the brackets

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1188,17,female,7.4,Instagram,7.4,2.0,3.76,1.7,high,10,1,4,0
1189,14,female,1.6,TikTok,4.8,2.4,2.97,1.9,low,9,9,10,0
1190,17,female,3.8,Instagram,8.4,0.9,3.60,1.9,high,1,2,2,0
1191,19,male,8.0,TikTok,4.7,0.5,2.18,0.6,medium,8,8,6,1
1192,13,male,7.8,TikTok,5.9,1.5,3.31,1.9,high,10,1,10,0
1193,13,female,7.2,Instagram,8.1,2.1,2.52,0.4,medium,3,3,7,0
1194,17,male,2.0,Both,4.5,1.7,2.65,0.0,medium,9,4,2,0
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [28]:
df.shape # total number of columns and rows in your dataset

(1200, 13)

In [29]:
df.info() # the most useful method in pandas
# showa a breakdown of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB

In [30]:
df.describe() # the numbers at a glance
# shows the measures of central tendency of your dataset(mean,total no of entries etc)

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

# These do not have brackets since they are **ATTRIBUTES**

In [32]:
df.columns # the column names

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='object')

In [33]:
df.dtypes # the tpye of each column

age                           int64
gender                       object
daily_social_media_hours    float64
platform_usage               object
sleep_hours                 float64
screen_time_before_sleep    float64
academic_performance        float64
physical_activity           float64
social_interaction_level     object
stress_level                  int64
anxiety_level                 int64
addiction_level               int64
depression_label              int64
dtype: object

In [34]:
df.index # the row labels

RangeIndex(start=0, stop=1200, step=1)

In [35]:
df.size # total number of cells

15600

In [36]:
df['age'].unique() # what values appear in the dataset under the given column

array([14, 19, 17, 15, 18, 16, 13])

In [37]:
df['age'].nunique() # how many distinct values are present in a given column

7

In [40]:
df["gender"].unique()

array(['male', 'female'], dtype=object)

In [41]:
df["gender"].nunique()

2

# Selecting columns - use square brackets **[]**

In [43]:
df[["age", "gender"]]  # two columns - DataFrame

      age  gender
0      14    male
1      19  female
2      17  female
3      15    male
4      15  female
...   ...     ...
1195   18  female
1196   16    male
1197   14  female
1198   15    male
1199   16  female

[1200 rows x 2 columns]

In [44]:
df["age"] # one column - a Series

0       14
1       19
2       17
3       15
4       15
        ..
1195    18
1196    16
1197    14
1198    15
1199    16
Name: age, Length: 1200, dtype: int64

In [46]:
df[["age", "gender", "depression_label"]] # dataframe

      age  gender  depression_label
0      14    male                 0
1      19  female                 0
2      17  female                 0
3      15    male                 0
4      15  female                 0
...   ...     ...               ...
1195   18  female                 0
1196   16    male                 0
1197   14  female                 0
1198   15    male                 0
1199   16  female                 0

[1200 rows x 3 columns]

# .**loc** and .**iloc**

In [57]:
df.loc[2, "age"] # row 2, column named age
# allows you to input the specific column name

np.int64(17)

In [4]:
df.iloc[2,0] # third row, first column (age) (incorporates indexes)
# you input the index of the desired column

NameError: name 'df' is not defined

In [5]:
df.iloc[5,0] # 6th row, first column(age)

NameError: name 'df' is not defined

In [51]:
df.iloc[2,2]

np.float64(1.3)

In [52]:
df.loc[0] # shows you info in the first row only

age                                14
gender                           male
daily_social_media_hours          7.9
platform_usage              Instagram
sleep_hours                       7.4
screen_time_before_sleep          2.9
academic_performance             3.01
physical_activity                 1.5
social_interaction_level          low
stress_level                        2
anxiety_level                       2
addiction_level                     1
depression_label                    0
Name: 0, dtype: object

In [53]:
df.loc[0:2] # shows you the first 3 rows

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0

In [54]:
df.iloc[0]

age                                14
gender                           male
daily_social_media_hours          7.9
platform_usage              Instagram
sleep_hours                       7.4
screen_time_before_sleep          2.9
academic_performance             3.01
physical_activity                 1.5
social_interaction_level          low
stress_level                        2
anxiety_level                       2
addiction_level                     1
depression_label                    0
Name: 0, dtype: object

In [56]:
df.iloc[0:2] # showa you the first and second row.....indices are applied

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0